title: "Matt Holt"
theme: "eon"
baseURL: "https://mholt.github.io/blogtest"
#baseURL: 'http://localhost:8801'
# for multiple authors, see
# https://discourse.gohugo.io/t/site-author-usage/31459/8?u=coolaj86
Author:
  name: "Matt Holt"
  email: "frederik.ring@gmail.com"
copyright: "© Matt Holt"
languageCode: "en-us"

Params:
  gravatar: true
  show_edit: "Suggest Edit"
  git_repo: "https://github.com/mholt/blogtest"
  git_branch: "main"
  git_host: "github"
  utterences_repo: "mholt/blogtest"
  utterences_term: "pathname"
  enableGitInfo: true
  enableEmoji: true

markup:
  goldmark:
    renderer:
    # unsafe allows use of HTML and JavaScript in your Markdown
    # disable if your blog allows posts from untrusted authors
    unsafe: true
